version: '3.8'

services:
  backend:
    build: ./
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      sportify:
    restart: always
    tty: true
    environment:
      SPRING_PROFILES_ACTIVE: prod

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      sportify:
    restart: always
    tty: true

networks:
  sportify:

