server:
  port: 8080

spring:
  profiles:
    active: local
    group:
      local: local, vworld
      dev:
      prod:

jwt:
  header: Authorization
  secret: dGhpcyBpcyBteSBoaWRkZW4gand0IGtleSBmb3IgdGVzdCwgcGxlYXNlIGdpdmUgbWUgand0IGtleSBoYWhhaGFoYWhh==
  access-token-validity-in-seconds: 360000